apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-container
          image: rsoreg.azurecr.io/admin-service:2.1.4
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERS_URL
              value: mongodb://shared-mongo-service:27017/users
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5

      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP