apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-container
          image: rsoreg.azurecr.io/admin-service:1.0.2
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_USERS_URL
              value: mongodb://shared-mongo-service:27017/users
      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP