apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  labels:
    app: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health-container
          image: rsoreg.azurecr.io/health-service:1.0.1
          ports:
            - containerPort: 8090
          env:
            - name: MONGO_USERS_URL
              value: mongodb://shared-mongo-service:27017/health
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            timeoutSeconds: 5

      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: health
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP