apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login-container
          image: rsoreg.azurecr.io/login-service:2.0.3
          ports:
            - containerPort: 8084
          env:
            - name: MONGO_USERS_URL
              value: mongodb://shared-mongo-service:27017/users
            - name: CONSUL_HTTP_ADDR
              value: http://consul-service:8500
            - name: CONSUL_CONNECT_SERVICE_NAME
              value: login-service
      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP