apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-mongo-service
  labels:
    app: order-mongo
spec:
  selector:
    app: order-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongo-deployment
  labels:
    app: order-mongo
spec:
  selector:
    matchLabels:
      app: order-mongo
  template:
    metadata:
      labels:
        app: order-mongo
    spec:
      containers:
        - name: order-mongo
          image: rsoreg.azurecr.io/mongo:3.6.17-xenial
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: order-mongo-pvc
              mountPath: /data/db/orders
      volumes:
        - name: order-mongo-pvc
          persistentVolumeClaim:
            claimName: order-mongo-pvc
      imagePullSecrets:
        - name: guidesecret