apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: rsoreg.azurecr.io/order-service:2.0.1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_ORDER_URL
              value: mongodb://order-mongo-service:27017/orders
      imagePullSecrets:
      - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP