apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-container
          image: rsoreg.azurecr.io/product-service:2.0.4
          ports:
            - containerPort: 8083
          env:
            - name: MONGO_PRODUCTS_URL
              value: mongodb://product-mongo-service:27017/products
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            timeoutSeconds: 5

      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP