apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: rsoreg.azurecr.io/user-service:2.0.3
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_USERS_URL
              value: mongodb://shared-mongo-service:27017/users
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
      imagePullSecrets:
        - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP